name: SkyEnvoys
version: ${project.version}
main: me.zoon20x.skyenvoys.SkyEnvoys
api-version: 1.16
authors: [ Zoon20X ]
description: new and imporved envoy system for servers

commands:
  adminEnvoys:
    usage: /<command>
